"""Add avatar, phone, bio and created_at to User model

Revision ID: 253c424c1ca1
Revises: f3890e0111c8
Create Date: 2025-05-27 11:40:42.335178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253c424c1ca1'
down_revision = 'f3890e0111c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
